name: LiminalityPress
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Liminality Press
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3b3b3c'
    - '#babcbe'
    - '#8e9093'
  brandStrength: 0.26557883620262146
  lightness: 0.8749485847074538
  saturation: 0.8337487678509206
  rhythmicContrast: 0.17924902914091945
purpose: []
